---
- name:
  hosts: aristaswitchessecure
  gather_facts: no

  vars:
    ansible_ssh_pass: alta3

  tasks:
  - name: Config DNS
    cli_config:
      config: ip name-server 8.8.8.8

  - name: Check config
    cli_command:
      command: show run | i ip name-server
    register: results

  - name: Print stdout
    debug:
      var: results.stdout
