---
 - name: "Install EPEL libraries in YUM" 
   hosts: planetexpress
   become: yes
     #connection: ssh
     #gather_facts: true

   tasks:

     - name: "Install epel-release" 
       ansible.builtin.yum:
         name: epel-release
         state: present
           #become: yes # run as sudo
       when: ansible_distribution == "CentOS"

     - name: "Update yum repos and Install package x"
       ansible.builtin.yum:
         update_cache: True
         name: 
           - fail2ban
           - moon-buggy
         state: present
           #become: yes # run as sudo
       when: ansible_distribution == "CentOS"
