---
- name: Building Precheck Failures
  hosts: arista_switches
  connection: network_cli
  become: yes
  become_method: enable
  gather_facts: yes

  vars:
    ansible_ssh_pass: alta3

  tasks:
  # dig into data we want to show
  - name: Get net ifaces
    debug:
      var: ansible_facts