---
- name:
  hosts: localhost
  connection: local

  vars:
    majortom: 'http://api.open-notify.org/astros.json'

  tasks:
  - name: "Send an HTTP GET to API"
    ansible.builtin.uri:
      method: GET
      url: "{{ majortom }}"
    register: data

  - name: "Use debug to show var contents"
    ansible.builtin.debug:
      msg: "{{ data }}"

  - name: "Return only json from data var"
    ansible.builtin.debug:
      msg: "{{ data.get('json') }}"

  - name: "Use debug and iterate across JSON"
    ansible.builtin.debug:
      msg: "On the {{ item.get('craft') }} is: {{ item.get('name') }}"
    loop: "{{ data.get('json').get('people') }}"