---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no

  vars_files:
    - /home/student/mycode/vars/planetexpress.yml

  tasks:
    - name: Configure spaceship registration
      template: 
        src: /home/student/mycode/templates/ship.cfg.j2
        dest: ~/ship.cfg

    - name: Configure mission orders 
      template: 
        src: /home/student/mycode/templates/mission-orders.txt.j2
        dest: ~/mission-orders.txt
