---
- name: Exploring the template module and jinja expressions
  hosts: planetexpress
  gather_facts: no

  vars: 
    ship_name: Bessie
    ship_type: Intergalactice
    engines: Dark Matter 
    dark_matter_balls: 63
    backup_engines: Chemical 

  tasks:
    - name: Configure spaceship registration
      template: 
        src: /home/student/mycode/templates/ship.cfg.j2
        dest: ~/ship.cfg
