---
- name: Playbook - Install figliet #metadata
  hosts: planetexpress:!farnsworth
  connection: ssh
  gather_facts: yes

  tasks:
  - name: using apt to install figlet
    ansible.builtin.apt:
      name: figlet
      state: present
    become: yes
