---
- name: "Exploring ansible raw"
  hosts: tx_mid_svr
  connection: ssh
  gather_facts: no
  # forks: 5

  tasks:
  - name: "Create file via ssh"
    raw: echo $HOSTNAME > newfile01.txt

  - name: "Create 2nd file via ssh"
    raw: echo "Hellow world" > newfile02.txt