---
- name: "Exploring ansible raw"
  hosts: tx_mid_svr
  connection: ssh
  gather_facts: no
  # forks: 5

  tasks:
  - name: "Create file via copy module"
    ansible.builtin.copy:
      content: ansible_env.LOGNAME
      dest: newfile01.txt
      force: yes

  - name: "Create 2nd file via ssh"
    ansible.builtin.copy:
      content: "Hello World!"
      dest: newfile02.txt
      force: yes
